baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Moritz-Maria von Igelfeld
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Presentation
          url: presentation/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts Frank Cong Wang's research papers, presentation, data, curriculum vitae, and contact information."
    author:FrankCong Wang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr Frank Cong Wang
          subtitle: "I am a post doc in School of physics, Peking University."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Presentation
              url: Presentation/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:igelfeld@regensburg.edu
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/
        - name: GitHub
          url: https://github.com/pmichaillat

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: ""
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
